# Generated by Django 2.2 on 2019-04-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pub_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_name', models.CharField(max_length=150)),
                ('pub_lat', models.FloatField()),
                ('pub_lon', models.FloatField()),
                ('pub_street', models.CharField(max_length=150)),
            ],
        ),
    ]
